# -*- coding: cp1252 -*-
from Tkinter import *
from tkMessageBox import *
from PIL import Image, ImageTk
import sqlite3
con=sqlite3.Connection("hotel")
cur=con.cursor()
cur.execute("create table if not exists hot(doa varchar(10),name varchar(20),nop number,mobile number(10),idproof varchar(20),idno number(10),nod number(2),amt number)")
pd=Tk()

pd.title("Personal Info.")
global pay
def insert(root):
    root.destroy()
    ins=Tk()
    ins.title("Booking Window")        
    x=IntVar()
    Label(ins,text="Select Your Room Type:",font='9').grid(row=1,column=3,sticky='w')
    Checkbutton(ins,text="Std/Single bed",variable=x,onvalue=1).grid(row=2,column=1)
    Checkbutton(ins,text="Std/Double bed",variable=x,onvalue=2).grid(row=2,column=2)
    Checkbutton(ins,text="Delux/Single bed",variable=x,onvalue=3).grid(row=2,column=3)
    Checkbutton(ins,text="Delux/Double bed",variable=x,onvalue=4).grid(row=2,column=4)
    Checkbutton(ins,text="Honeymoon Suite",variable=x,onvalue=5).grid(row=2,column=5)
    Label(ins,text="Enter Date of Arival(DD/MM/YY):").grid(row=3,column=2,sticky='w')
    d=Entry(ins)
    d.grid(row=3,column=4)
    Label(ins,text="Enter Your Name:").grid(row=4,column=2,sticky='w')
    n=Entry(ins)
    n.grid(row=4,column=4)
    Label(ins,text="Enter no of peoples:").grid(row=5,column=2,sticky='w')
    no=Entry(ins)
    no.grid(row=5,column=4)
    Label(ins,text="Enter Your Contact No.").grid(row=6,column=2,sticky='w')
    mob=Entry(ins)
    mob.grid(row=6,column=4)
    Label(ins,text="Enter Id Proof").grid(row=7,column=2,sticky='w')
    i=Entry(ins)
    i.grid(row=7,column=4)
    Label(ins,text="Enter Id Proof no").grid(row=8,column=2,sticky='w')
    idn=Entry(ins)
    idn.grid(row=8,column=4)
    Label(ins,text="Enter no. of days to stay").grid(row=9,column=2,sticky='w')
    nod=Entry(ins)
    nod.grid(row=9,column=4)
    a=()
    def pri(x):
        pay=0
        if x==1:
            pay=800*int(nod.get())
        elif (x==2):
            pay=1500*int(nod.get())
        elif (x==3):
            pay=1500*int(nod.get())
        elif (x==4):
            pay=2700*int(nod.get())
        elif(x==5):
            pay=3500*int(nod.get())
        print pay,x
        a=(d.get(),n.get(),int(no.get()),int(mob.get()),i.get(),int(idn.get()),int(nod.get()),pay)
        result=askyesno("Confirm","Contiue to payment\n(Amount=%d)"%pay)
        if result==True:
            cur.execute("insert into hot values (?,?,?,?,?,?,?,?)",a)
            con.commit()
            print a
            showinfo("Confirm","Your booking has been confirmed.\nJust bring your valid id proof with u")
            cur.execute("select * from hot")
            a=cur.fetchall()
            print a
    Button(ins,text='Pay',command=lambda:pri(int(x.get()))).grid(row=10,column=4,sticky=N+W+E+S)
    Button(ins,text='Go Back',command=ins.destroy).grid(row=10,column=2,sticky=N+W+E+S)
    ins.mainloop()
def cnc():
    cn=Tk()
    cn.title("Cancel Your Booking")
    def ser():
        p=n.get()
        cur.execute("select * from hot where name=?",(p,))
        a=cur.fetchall()
        result=askyesno("Confirm","Is this entry correct\n%s"%a)
        if result==True:
            result1=askyesno("Confirm","Do u really want to cancel booking")
            if result1==True:
                cur.execute("delete from hot where name=?",(p,))
                showinfo("Result","Your booking has Cancelled")
                cur.execute("select * from hot")
                a=cur.fetchall()
                print a
    Label(cn,text="Cancel Your Booking",font="9").grid(row=1,column=1,columnspan=10)
    Label(cn,text="Enter name ").grid(row=2,column=1)
    Button(cn,text="Search",command=ser).grid(row=3,column=1,columnspan=2)
    n=Entry(cn)
    n.grid(row=2,column=4)
    cn.mainloop()
    
    
def room_d():
    room=Tk()
    room.title("Room Details & Rates")
    Label(room,text="ROOM RATES",font="timesnewroman 15 bold").grid(row=1,column=1)
    Label(room,text="Standard(Non AC)",font="10").grid(row=2,column=1)
    Label(room,text="Single Bed",font="10").grid(row=2,column=3)
    Label(room,text="Rs. 800/night",font="10").grid(row=2,column=4)
    Label(room,text="Double Bed",font="10").grid(row=3,column=3)
    Label(room,text="Rs. 1500/night",font="10").grid(row=3,column=4)
    Label(room,text="Delux sweet",font="10").grid(row=4,column=1,sticky=W)
    Label(room,text="Single Bed",font="10").grid(row=4,column=3)
    Label(room,text="Rs. 1500/night",font="10").grid(row=4,column=4)
    Label(room,text="Double Bed",font="10").grid(row=5,column=3)
    Label(room,text="Rs. 2700/night",font="10").grid(row=5,column=4)
    Label(room,text="Honeymoon Suite",font="10").grid(row=6,column=1)
    Label(room,text="Rs. 3500/night",font="10").grid(row=6,column=4)
    Button(room,text='EXIT',command=room.destroy).grid(row=7,column=3,sticky=N+W+E+S)
    room.mainloop()
def miss():
    mission=Tk()
    mission.title("Hotel`s Mission")
    Label(mission,text="Mision",font="timesnewroman 15 bold").grid(row=1,column=1,sticky=W)
    Label(mission,text="Our Guests :",font="9").grid(row=2,column=1,sticky=W)
    Label(mission,text="We are committed to meeting and exceeding the expectations of our guests through our unremitting dedication to every aspect of service.",font="9").grid(row=3,column=2,sticky=W)
    Label(mission,text="Our People :",font="9").grid(row=4,column=1,sticky=W)
    Label(mission,text="We are committed to the growth, development and welfare of our people upon whom we rely to make this happen.",font="9").grid(row=5,column=2,sticky=W)
    Label(mission,text="Our Distinctiveness :",font="9").grid(row=6,column=1,sticky=W)
    Label(mission,text="Together, we shall continue the Oberoi tradition of pioneering in the hospitality industry, striving for unsurpassed excellence in",font="9").grid(row=7,column=2,sticky=W)
    Label(mission,text="high potential locations all the way from the Middle East to the Asia-Pacific.",font="9").grid(row=8,column=2,sticky=W)
    Label(mission,text="Our Shareholders :",font="9").grid(row=9,column=1,sticky=W)
    Label(mission,text="As a result, we will create extraordinary value for our shareholders.",font="9").grid(row=10,column=2,sticky=W)
    Button(mission,text='EXIT',command=mission.destroy).grid(row=11,column=1,columnspan=2,sticky=N+W+E+S)
    mission.mainloop()
def obj():
    objec=Tk()
    objec.title("Hotel`s Vision")
    Label(objec,text="Vision",font="timesnewroman 15 bold").grid(row=1,column=1)
    Label(objec,text=">",font="9").grid(row=2,column=1,sticky=W)
    Label(objec,text="We see an organisation which aims at leadership in the hospitality industry by understanding its guests;",font="9").grid(row=2,column=2,sticky=W)
    Label(objec,text="and designing and delivering products and services which enable it to exceed their expectations.",font="9").grid(row=3,column=2,sticky=W)
    Label(objec,text=">",font="9").grid(row=4,column=1,sticky=W)
    Label(objec,text="We will always demonstrate care for our customers through anticipation of their needs, warmth and concern.",font="9").grid(row=4,column=2,sticky=W)
    Label(objec,text=">",font="9").grid(row=5,column=1,sticky=W)
    Label(objec,text="We see a lean and responsive organisation where decision making is encouraged at each level and which accepts",font="9").grid(row=5,column=2,sticky=W)
    Label(objec,text="change. An organisation that is committed and responsive to its guests and other stakeholders.",font="9").grid(row=6,column=2,sticky=W)
    Label(objec,text=">",font="9").grid(row=7,column=1,sticky=W)
    Label(objec,text="We see a multi-skilled workforce; which consists of team players who have pride of ownership in translating",font="9").grid(row=7,column=2,sticky=W)
    Label(objec,text="the organization`s vision into reality",font="9").grid(row=7,column=2,sticky=W)
    Label(objec,text=">",font="9").grid(row=8,column=1,sticky=W)
    Label(objec,text="We see an organisation where people are nurtured through continuous learning and skill improvement; and are",font="9").grid(row=9,column=2,sticky=W)
    Label(objec,text="respected, heared and encouraged to do their best. The Oberoi Group is recognised as best practice for",font="9").grid(row=10,column=2,sticky=W)
    Label(objec,text="training and developing its peoples.",font="9").grid(row=11,column=2,sticky=W)
    Label(objec,text=">",font="9").grid(row=12,column=1,sticky=W)
    Label(objec,text="We see the world dotted with hotels of The Oberoi Group, in strategic commercial and resort locations.",font="9").grid(row=12,column=2,sticky=W)
    Label(objec,text=">",font="9").grid(row=13,column=1,sticky=W)
    Label(objec,text="We see user-friendly technology enhancing value for our customers and helping our personnel by making",font="9").grid(row=13,column=2,sticky=W)
    Label(objec,text="information more aceessible.",font="9").grid(row=14,column=2,sticky=W)
    Label(objec,text=">",font="9").grid(row=15,column=1,sticky=W)
    Label(objec,text="We see an organisation which is conscious of its role in the community, supporting social needs and ensuring",font="9").grid(row=15,column=2,sticky=W)
    Label(objec,text="employment from within the local community.",font="9").grid(row=16,column=2,sticky=W)
    Button(objec,text='EXIT',command=objec.destroy).grid(row=17,column=2,columnspan=2,sticky=N+W+E+S)
    objec.mainloop()
def deta():
    detail=Tk()
    detail.title("Check In\out Rules")
    Label(detail,text="Check in & Check out",font="timesnewroman 15 bold").grid(row=1,column=1,columnspan=2)
    Label(detail,text=">",font="9").grid(row=2,column=1,sticky=W)
    Label(detail,text="Check-in time is 14:00 (2pm) Check-out time is 12:00 (noon). 24hour reception.",font="9").grid(row=2,column=2,sticky=W)
    Label(detail,text=">",font="9").grid(row=3,column=1,sticky=W)
    Label(detail,text="Late check out / early check in should be extra paid and prearranged.",font="9").grid(row=3,column=2,sticky=W)
    Label(detail,text=">",font="9").grid(row=4,column=1,sticky=W)
    Label(detail,text="Early check in: the sum is equal to half-day accommodation if a guest arrives 8.00 (8 am) – 14.00 (2pm);",font="9").grid(row=4,column=2,sticky=W)
    Label(detail,text="the sum is equal to full-day accommodation if a guest arrives before 8.00 (8 am).",font="9").grid(row=5,column=2,sticky=W)
    Label(detail,text=">",font="9").grid(row=6,column=1,sticky=W)
    Label(detail,text="Late check out / early check in might be complimentary if agreed with booking department",font="9").grid(row=6,column=2,sticky=W)
    Label(detail,text="Accommodation Rules",font="timesnewroman 15 bold").grid(row=7,column=1,columnspan=2)
    Label(detail,text=">",font="9").grid(row=8,column=1,sticky=W)
    Label(detail,text="You are welcome to invite guests to your room for a period of 8.00 (8 am) - 23.00 (11pm) ",font="9").grid(row=8,column=2,sticky=W)
    Label(detail,text="daily. But your guests are to present their valid national ID card or passport, or ",font="9").grid(row=9,column=2,sticky=W)
    Label(detail,text="any other valid proof of identity to the relevant hotel employee immediately upon arrival.",font="9").grid(row=10,column=2,sticky=W)
    Label(detail,text=">",font="9").grid(row=11,column=1,sticky=W)
    Label(detail,text="Housekeeping services and frequency of towels & linen change may vary in different hotels",font="9").grid(row=11,column=2,sticky=W)
    Label(detail,text=">",font="9").grid(row=12,column=1,sticky=W)
    Label(detail,text="Breakfast is not included in price at some Acme hotels, for instance at apart-hotel and hostels.",font="9").grid(row=12,column=2,sticky=W)
    Label(detail,text=">",font="9").grid(row=13,column=1,sticky=W)
    Label(detail,text="Pets are prohibited at our hotels",font="9").grid(row=13,column=2,sticky=W)
    Label(detail,text=">",font="9").grid(row=14,column=1,sticky=W)
    Label(detail,text="Regretfully, our hotels do not feature any sets of hotel in-room toiletries such as bath gel, shampoo,",font="9").grid(row=14,column=2,sticky=W)
    Label(detail,text="conditioner, body lotion, bath salt, soap.",font="9").grid(row=15,column=2,sticky=W)
    Label(detail,text=">",font="9").grid(row=16,column=1,sticky=W)
    Label(detail,text="We welcome all travellers over the age of 18 in our hotels.Children under the age of 18 should stay at parents room.",font="9").grid(row=16,column=2,sticky=W)
    Label(detail,text=">",font="9").grid(row=17,column=1,sticky=W)
    Label(detail,text="Upon departing, guests are obliged to turn off all water faucets, as well as the lights in the room and its facilities,",font="9").grid(row=17,column=2,sticky=W)
    Label(detail,text="and to shut the door as they leave and its facilities, and to shut the door as they leave",font="9").grid(row=18,column=2,sticky=W)
    Label(detail,text=">",font="9").grid(row=19,column=1,sticky=W)
    Label(detail,text="Guests should always make sure that you know the location of the emergency exits, fire alarms and fire extinguishers",font="9").grid(row=19,column=2,sticky=W)
    Label(detail,text=">",font="9").grid(row=20,column=1,sticky=W)
    Label(detail,text="Guests are obliged to pay for any damage they cause, if they are unable to prove that they are not responsible for this damage.",font="9").grid(row=20,column=2,sticky=W)
    Label(detail,text=">",font="9").grid(row=21,column=1,sticky=W)
    Label(detail,text=" A guest knows and accepts that the video security system is installed in the hotel hallways and lobbies",font="9").grid(row=21,column=2,sticky=W)
    Button(detail,text='EXIT',command=detail.destroy).grid(row=22,column=2,columnspan=2,sticky=N+W+E+S)    
    detail.mainloop()
def desc():
    des=Tk()
    des.title("Description")
    Label(des,text="Description and Services",font="timesnewroman 15 bold").grid(row=1,column=1,columnspan=2)
    Label(des,text="Nestled in greenery, in the heart of Delhi, Fraser Suite a premier luxury hotel in the Capital, is acknowledged ",font="9").grid(row=2,column=1,sticky=W)
    Label(des,text="as the preferred 'Residence for World Leaders and Global Icons' for over 30 years. The 438 room property epitomizes",font="9").grid(row=3,column=1,sticky=W)    
    Label(des,text="luxury hotel experience with exemplary service and warm hospitality soaked in Indian traditions. The hotel has ",font="9").grid(row=4,column=1,sticky=W)
    Label(des,text="established industry benchmarks in safety and security, wide choice of premium rooms and suites, world renowned ",font="9").grid(row=5,column=1,sticky=W)
    Label(des,text="restaurants including the iconic Bukhara, banqueting facilities, spa and wellness, and more. ",font="9").grid(row=6,column=1,sticky=W)
    Label(des,text="A Capital Address",font="9").grid(row=7,column=1)
    Label(des,text="Situated in the Capital`s exclusive Diplomatic Enclave, the hotel is in close proximity to Delhi`s corridors of power.",font="9").grid(row=8,column=1,sticky=W)
    Label(des,text="The hotel has long been the favoured accommodation of heads of state, royalty and business leaders from across ",font="9").grid(row=9,column=1,sticky=W)
    Label(des,text="the world.Surrounded by the verdant, ridge fringed enclave of Chanakyapuri, the stateliness of Fraser aptly ",font="9").grid(row=10,column=1,sticky=W)
    Label(des,text="reflects the quiet dignity of its location.",font="9").grid(row=11,column=1,sticky=W)
    Label(des,text="Culinary Excellence",font="9").grid(row=12,column=1)
    Label(des,text="A significant feature on the itineraries of gourmets across the world, Fraser`s restaurants promise a unique",font="9").grid(row=13,column=1,sticky=W)
    Label(des,text="experience of authentic Indian and international cuisine. One of Delhi`s most popular dining destinations, the",font="9").grid(row=14,column=1,sticky=W)
    Label(des,text="hotel houses the internationally acclaimed Bukhara for Indian North-West frontier cuisine, which has been consistently",font="9").grid(row=15,column=1,sticky=W)
    Label(des,text="voted amongst the ''Top 50 Restaurants in the World'' and the ''Top 20 in Asia'', and Dum Pukht for royal Awadhi ",font="9").grid(row=16,column=1,sticky=W)
    Label(des,text="cuisine, recognized as one of the 'World`s Best Classic Restaurants' by Conde Nast Traveler Gold Standard.",font="9").grid(row=17,column=1,sticky=W)
    Label(des,text="Responsible Luxury",font="9").grid(row=18,column=1)
    Label(des,text="Fraser is a Green Hotel endorsing Responsible Luxury and is certified as the world`s first LEED EB* Platinum rated",font="9").grid(row=19,column=1,sticky=W)
    Label(des,text="hotel by the US Green Building Council (Leadership in Energy and Environmental Design in the existing building category).",font="9").grid(row=20,column=1,sticky=W)
    Label(des,text="Steeped in History",font="9").grid(row=21,column=1)
    Label(des,text="Fraser is a tribute to the illustrious Mauryan Dynasty which gave Indian history the Golden Age of art, architecture",font="9").grid(row=22,column=1,sticky=W)
    Label(des,text="and culture.The architecture of the hotel rises up in steps in the style of a Buddhist Stupa, and the central",font="9").grid(row=23,column=1,sticky=W)
    Label(des,text="lobby recreates the dome of a Buddhist Chaitya Hall which has been modelled from the ancient cave temples in Maharashtra.",font="9").grid(row=24,column=1,sticky=W)
    Button(des,text='EXIT',command=des.destroy).grid(row=25,column=1,columnspan=2,sticky=N+W+E+S)    
    des.mainloop()
def awar():
    aw=Tk()
    aw.title("Awards")
    Label(aw,text="HOTEL AWARDS",font="timesnewroman 15 bold").grid(row=1,column=1,sticky=W,columnspan=2)
    Label(aw,text=">",font="9").grid(row=2,column=1,sticky=W)
    Label(aw,text="Top Resorts in India (Ranked 5th) - Travel + Leisure, World's Best Awards, Readers' Survey 2016",font="9").grid(row=2,column=2,sticky=W)
    Label(aw,text=">",font="9").grid(row=3,column=1,sticky=W)
    Label(aw,text="Top 25 Hotels in India (Ranked 9th) - TripAdvisor, Travellers' Choice Awards 2016",font="9").grid(row=3,column=2,sticky=W)
    Label(aw,text=">",font="9").grid(row=4,column=1,sticky=W)
    Label(aw,text="Top 25 Luxury Hotels in India (Ranked 22nd) - TripAdvisor, Travellers' Choice Awards 2016",font="9").grid(row=4,column=2,sticky=W)
    Label(aw,text=">",font="9").grid(row=5,column=1,sticky=W)
    Label(aw,text="Asia's Leading Luxury Hotel 2015 - The World Travel Awards - Asia & Australasia, 2015",font="9").grid(row=5,column=2,sticky=W)
    Label(aw,text=">",font="9").grid(row=6,column=1,sticky=W)
    Label(aw,text="Best Five-Star Deluxe Hotel in India - National Tourism Awards 2015",font="9").grid(row=6,column=2,sticky=W)
    Label(aw,text=">",font="9").grid(row=7,column=1,sticky=W)
    Label(aw,text="Asia's Leading Luxury Hotel 2015 - World Travel Awards",font="9").grid(row=7,column=2,sticky=W)
    Label(aw,text=">",font="9").grid(row=8,column=1,sticky=W)
    Label(aw,text="Asia's Leading Luxury Hotel 2014 - World Travel Awards",font="9").grid(row=8,column=2,sticky=W)
    Label(aw,text=">",font="9").grid(row=9,column=1,sticky=W)
    Label(aw,text="The Fraser, New Delhi voted as the Best Hotel in New Delhi - DestinAsian -Reader's Choice Awards 2014",font="9").grid(row=9,column=2,sticky=W)
    Label(aw,text=">",font="9").grid(row=10,column=1,sticky=W)
    Label(aw,text="India's Leading Business Hotel 2013 - World Travel Awards",font="9").grid(row=10,column=2,sticky=W)
    Label(aw,text=">",font="9").grid(row=11,column=1,sticky=W)
    Label(aw,text="Ranked Best Business Hotel in Delhi - Travel + Leisure \"World's Best Business Hotels Awards\" survey 2013",font="9").grid(row=11,column=2,sticky=W)
    Label(aw,text=">",font="9").grid(row=12,column=1,sticky=W)
    Label(aw,text="Certificate of Excellence - TripAdvisor, 2013",font="9").grid(row=12,column=2,sticky=W)
    Label(aw,text=">",font="9").grid(row=13,column=1,sticky=W)
    Label(aw,text="Best Hotel in New Delhi - DestinAsian Readers Choice Awards 2012",font="9").grid(row=13,column=2,sticky=W)
    Label(aw,text=">",font="9").grid(row=14,column=1,sticky=W)
    Label(aw,text="Best Business Hotel in New Delhi - Business Traveller, Asia - Pacific Travel Awards 2012",font="9").grid(row=14,column=2,sticky=W)
    Label(aw,text=">",font="9").grid(row=15,column=1,sticky=W)
    Label(aw,text="Best Five Star Deluxe Hotel in India - National Tourism Awards 2011 - 2012",font="9").grid(row=15,column=2,sticky=W)
    Label(aw,text=">",font="9").grid(row=16,column=1,sticky=W)
    Label(aw,text="Favourite Business Hotel in India (Ranked 2nd) - CondNast Traveller, India, Readers' Travel Awards 2011",font="9").grid(row=16,column=2,sticky=W)
    Label(aw,text=">",font="9").grid(row=17,column=1,sticky=W)
    Label(aw,text="Top city hotels in Asia - Ranked amongst the top city hotels in Asia by the readers of Travel + Leisure, USA in 2011.",font="9").grid(row=17,column=2,sticky=W)
    Label(aw,text=">",font="9").grid(row=18,column=1,sticky=W)
    Label(aw,text="Best Hotel in New Delhi - DestinAsian, Readers' Choice Awards 2011",font="9").grid(row=18,column=2,sticky=W)
    Label(aw,text=">",font="9").grid(row=19,column=1,sticky=W)
    Label(aw,text="Best Overseas Business Hotels (Ranked 10th) - CondNast Traveller, UK, Readers' Travel Awards 2010",font="9").grid(row=19,column=2,sticky=W)
    Label(aw,text=">",font="9").grid(row=20,column=1,sticky=W)
    Label(aw,text="Best Business Hotel in New Delhi - Business Traveller, Asia - Pacific Travel Awards 2009",font="9").grid(row=20,column=2,sticky=W)
    Button(aw,text="EXIT",command=aw.destroy).grid(row=21,column=2,columnspan=2,sticky=N+W+E+S)
    aw.mainloop()
def touri():
    tour=Toplevel()
    tour.title("Tourism In Delhi")
    Label(tour,text="Tourism in Delhi",font="timesnewroman 17 bold").grid(row=1,column=1,columnspan=2)
    Label(tour,text="Garden of Five Senses",font="timesnewroman 15 italic").grid(row=2,column=1)
    Label(tour,text="The Garden of Five Senses is not just a park, it is a space with a variety of activities, inviting public",font="9").grid(row=3,column=1,sticky=W)
    Label(tour,text="interaction and exploration. The project, developed by Delhi Tourism Transportation Development",font="9").grid(row=4,column=1,sticky=W)
    Label(tour,text="Corporation, was conceptualized to answer to the city's need for leisure space for the public, for people ",font="9").grid(row=5,column=1,sticky=W)
    Label(tour,text="to socialize and unwind.Such spaces add atmosphere and life to a city and cater to all sections of the society.",font="9").grid(row=6,column=1,sticky=W)
    Label(tour,text="Iskcon Temple",font="timesnewroman 15 italic").grid(row=7,column=1)
    Label(tour,text="Iskcon, East of Kailash has developed Vedic Expo , Asias only technology center promoting Vedic Sciences and",font="9").grid(row=8,column=1,sticky=W)
    Label(tour,text="culture wherein a very high technology usage of Audio ,visual presentation of Bhagvat Gita is depicted with",font="9").grid(row=9,column=1,sticky=W)
    Label(tour,text="lights and sound used for creating historical effect and a very interesting tourist attraction.",font="9").grid(row=10,column=1,sticky=W)
    Label(tour,text="They have another show on Mahabharata and also a complete robotics show . The whole ambience of the",font="9").grid(row=11,column=1,sticky=W)
    Label(tour,text="temple is very attractive with ongoing devotional chants, fountains and gift shops.They have a Govinda’s",font="9").grid(row=12,column=1,sticky=W)
    Label(tour,text="restaurant serving high quality vegetarian food and has become land mark for foodies in Delhi.",font="9").grid(row=13,column=1,sticky=W)
    Label(tour,text="Humayun`s Tomb",font="timesnewroman 15 italic").grid(row=14,column=1)
    Label(tour,text="Located near the crossing of Mathura road and Lodhi road, this magnificent garden tomb is the first substantial",font="9").grid(row=15,column=1,sticky=W)
    Label(tour,text="example of Mughal architecture in India.",font="9").grid(row=16,column=1,sticky=W)
    Label(tour,text="It was built in 1565 A.D. nine years after the death of Humayun, by his senior widow Bega Begam. Inside the",font="9").grid(row=17,column=1,sticky=W)
    Label(tour,text="walled enclosure the most notable features are the garden squares (chaharbagh) with pathways water channels,",font="9").grid(row=18,column=1,sticky=W)
    Label(tour,text="centrally located well proportional mausoleum topped by double dome.",font="9").grid(row=19,column=1,sticky=W)
    Label(tour,text="& many more........",font="9").grid(row=20,column=1,sticky=W)
    Button(tour,text="EXIT",command=tour.destroy).grid(row=21,column=1,columnspan=2,sticky=N+W+E+S)
    tour.mainloop()
def event():
    eve=Tk()
    eve.title("Plan An Event")
    Label(eve,text="Royal Retreat",font="timesnewroman 15 bold").grid(row=1,column=1,sticky=W)
    Label(eve,text="Our meeting rooms, business centre and ballrooms are located off a dramatic sandstone and white marble",font="9").grid(row=2,column=1,sticky=W)
    Label(eve,text=" pre-function area.",font="9").grid(row=3,column=1,sticky=W)
    Label(eve,text="The high ceilinged ballroom, which has exclusive access to the Mughal inspired banquet garden, can be used",font="9").grid(row=4,column=1,sticky=W)
    Label(eve,text="in its entirety, or divided into two smaller rooms.",font="9").grid(row=5,column=1,sticky=W)
    Label(eve,text="The banquet halls can be used individually, or combined for larger meetings or conferences, while our fully",font="9").grid(row=6,column=1,sticky=W)
    Label(eve,text="equipped business centre is suitable for conducting breakaway sessions, or interviews",font="9").grid(row=7,column=1,sticky=W)
    Label(eve,text="Beach Resorts",font="timesnewroman 15 bold").grid(row=8,column=1,sticky=W)
    Label(eve,text="The Oberoi, Sahl Hasheesh features a range of beach, poolside and in-room private dining venues for romantic",font="9").grid(row=9,column=1,sticky=W)
    Label(eve,text="occasions, exclusive parties and professional events. Our team of experienced, qualified staff will handle",font="9").grid(row=10,column=1,sticky=W)
    Label(eve,text="every aspect of planning, organisation and implementation, while menus can be chosen from the carte or",font="9").grid(row=11,column=1,sticky=W)
    Label(eve,text="designed in collaboration with our chefs.",font="9").grid(row=12,column=1,sticky=W)
    Label(eve,text="Our PADI-certified dive centre is a superb choice for corporate enrichment initiatives, while the smart,",font="9").grid(row=13,column=1,sticky=W)
    Label(eve,text="professional meeting room is suitable for hosting training seminars, senior level and Board meetings",font="9").grid(row=14,column=1,sticky=W)
    Button(eve,text="EXIT",command=eve.destroy).grid(row=15,column=1,sticky=N+W+E+S)
    eve.mainloop()
def direction():
    dire=Toplevel()
    dire.title("Directions to our Hotel")
    Label(dire,text="Directon to Fraser Suites",font="timesnewroman 15 bold").grid(row=1,column=1,columnspan=10,sticky=N+W+E+S)
    background_image=ImageTk.PhotoImage(Image.open("map.jpg"))
    background_label =Label(dire,image=background_image,compound='right').grid(row=2,column=1,columnspan=30)
    Label(dire,text=">",font="10").grid(row=3,column=1,sticky=W)
    Label(dire,text="Fraser Suites is situated in Mayur Vihar, at a 5 minutes walking distance from the metro station. A stone's throw away from cultural and tourist places",font="10").grid(row=3,column=2,sticky=W)
    Label(dire,text="like Red Fort, Jama Masjid, Chandni Chowk, Sanjay Lake, Lodi Gardens and Qutab Minar, this hotel is the perfect fusion of comfort and easy convenience",font="10").grid(row=4,column=2,sticky=W)
    Label(dire,text=">",font="10").grid(row=5,column=1,sticky=W)
    Label(dire,text="Distance from Indra Gandhi Airport: Approx. 24km",font="10").grid(row=5,column=2,sticky=W)
    Label(dire,text=">",font="10").grid(row=6,column=1,sticky=W)
    Label(dire,text="Distance from New Delhi Railway Station: Approx. 12km",font="10").grid(row=6,column=2,sticky=W)
    Label(dire,text=">",font="10").grid(row=7,column=1,sticky=W)
    Label(dire,text="Distance from Nizzamuddin Railway Station: Approx. 8km",font="10").grid(row=7,column=2,sticky=W)
    Button(dire,text="EXIT",command=dire.destroy).grid(row=8,column=2,sticky=N+W+E+S)
    dire.mainloop()
def contact():
    cont=Tk()
    cont.title("Contact Us")
    Label(cont,text="Corporate Offices",font="timesnewroman 15 bold").grid(row=1,column=1,sticky=W)
    Label(cont,text="Reservation Queries",font="timesnewroman 12 bold").grid(row=2,column=1,sticky=W)
    Label(cont,text="Fraser Contact Centre\nEmail: reservations@frasergroup.com\nTelephone: +91-11-2389 0606\nFacsimile : +91-11-2389 0500\nAddress:\nFraser Hotels & Resorts\n7, Sham Nath Marg, Delhi-110 054, India",font="9").grid(row=3,column=1,sticky=W)
    Label(cont,text="Marketing Queries",font="timesnewroman 12 bold").grid(row=4,column=1,sticky=W)
    Label(cont,text="Corporate Marketing\nEmail: e.marketing@frasergroup.com\nTelephone: +91-11-2389 0505\nFacsimile : +91-11-2389 0582\nAddress:\nFraser Hotels & Resorts\n7, Sham Nath Marg, Delhi-110 054, India",font="9").grid(row=5,column=1,sticky=W)
    Button(cont,text="EXIT",command=cont.destroy).grid(row=6,column=1,sticky=N+W+E+S)
    cont.mainloop()
def made():
    pd.destroy()
    root=Tk()
    root.title("HOTEL CHECK IN/OUT MANAGEMENT SYSTEM")
    Label(root,text="FRASER SUITES",font="Aerial 20 italic").grid(row=1,column=1,sticky=W,columnspan=3)
    Label(root,text="Plot No 4A, District Center, Phase-1,",font="Aerial 15 ").grid(row=2,column=1,columnspan=3,sticky=W)
    Label(root,text="Mayur Vihar, New Delhi, Delhi 110091",font="Aerial 15 ").grid(row=3,column=1,columnspan=3,sticky=W)
    Label(root,text="Check Out at 12 AM",bg="red",width=113).grid(row=4,column=1,columnspan=6)
    Button(root,text='Room & Rates',command=room_d,width=17).grid(row=5,column=1,sticky=W)
    Button(root,text='Hotel`s Mission',command=miss,width=17).grid(row=5,column=2,sticky=W)
    Button(root,text='Hotel`s Vision',command=obj,width=18).grid(row=5,column=3,sticky=W)
    Button(root,text='Check In/Out rules',command=deta,width=18).grid(row=5,column=4,sticky=W)
    Button(root,text='Description',command=desc,width=17).grid(row=5,column=5,sticky=W)
    Button(root,text='Awards',command=awar,width=18).grid(row=5,column=6,sticky=W)
    background_image=ImageTk.PhotoImage(Image.open("rsz_1hotel.jpg"))
    background_label =Label(root,image=background_image,compound='right').grid(row=6,column=1,columnspan=10,sticky='w')
    Button(root,text='Tourism',command=touri,width=17).grid(row=7,column=1,sticky=W)
    Button(root,text='Events',width=17,command=event).grid(row=7,column=2,sticky=W)
    Button(root,text='Location',width=18,command=direction).grid(row=7,column=3,sticky=W)
    Button(root,text='Book Rooms',width=18,command=lambda:insert(root)).grid(row=7,column=4,sticky=W)
    Button(root,text='Cancel Booking',width=17,command=cnc).grid(row=7,column=5,sticky=W)
    Button(root,text='Contact us',width=18,command=contact).grid(row=7,column=6,sticky=W)
    root.mainloop()
Label(pd,text="HOTEL CHECK IN/OUT MANAGEMENT SYSTEM",font="Aerial 20 ",bd=5).grid(row=1,column=1,columnspan=3)
Label(pd,text="Name",font="Aerial 10 bold").grid(row=2,column=1,sticky=E)
Label(pd,text=":",font="Aerial 10 bold").grid(row=2,column=2)
Label(pd,text="Shikhar Mittal",font="Aerial 10 bold").grid(row=2,column=3,sticky=W)
Label(pd,text="Enrollment No.",font="Aerial 10 bold").grid(row=3,column=1,sticky=E)
Label(pd,text=":",font="Aerial 10 bold").grid(row=3,column=2)
Label(pd,text="151390",font="Aerial 10 bold").grid(row=3,column=3,sticky=W)
Label(pd,text="Batch",font="Aerial 10 bold").grid(row=4,column=1,sticky=E)
Label(pd,text=":",font="Aerial 10 bold").grid(row=4,column=2)
Label(pd,text="BY(B5)",font="Aerial 10 bold").grid(row=4,column=3,sticky=W)
Label(pd,text="Branch",font="Aerial 10 bold").grid(row=5,column=1,sticky=E)
Label(pd,text=":",font="Aerial 10 bold").grid(row=5,column=2)
Label(pd,text="Computer Science ",font="Aerial 10 bold").grid(row=5,column=3,sticky=W)
Label(pd,text="& Engineering",font="Aerial 10 bold").grid(row=6,column=3,sticky=W)
Label(pd,text="Course",font="Aerial 10 bold").grid(row=7,column=1,sticky=E)
Label(pd,text=":",font="Aerial 10 bold").grid(row=7,column=2)
Label(pd,text="B. Tech (IInd Year)",font="Aerial 10 bold").grid(row=7,column=3,sticky=W)
Label(pd,text="Contact no.",font="Aerial 10 bold").grid(row=8,column=1,sticky=E)
Label(pd,text=":",font="Aerial 10 bold").grid(row=8,column=2)
Label(pd,text="+91-7309094867",font="Aerial 10 bold").grid(row=8,column=3,sticky=W)
Label(pd,text="E. Mail id",font="Aerial 10 bold").grid(row=9,column=1,sticky=E)
Label(pd,text=":",font="Aerial 10 bold").grid(row=9,column=2)
Label(pd,text="shikhar.mittal2@outlook.com",font="Aerial 10 bold").grid(row=9,column=3,sticky=W)
Label(pd,text="Submitted To",font="Aerial 10 bold").grid(row=10,column=1,sticky=E)
Label(pd,text=":",font="Aerial 10 bold").grid(row=10,column=2)
Label(pd,text="Dr. Mahesh Kumar",font="Aerial 10 bold").grid(row=10,column=3,sticky=W)
Button(pd,text="Press To Proceed To Project",font="ariel 15 bold",bd=5,relief='ridge',command=made).grid(row=11,column=1,columnspan=3,sticky='nwes')
pd.mainloop()


